### ISSUE TITLE
Is Bitbucket supported?

### ISSUE THREAD

**Issue by parched** [TeaCI/tea-ci#2]
Drone supported Bitbucket but I couldn't figure out how to use it here.

**Comment by ghost** [comment]
@parched welcome to use Tea CI.

I didn't enable Bitbucket, but that's possible: http://docs.tea-ci.org/setup/remotes/bitbucket/

@felixonmars could you reconfigure Tea CI and restart the CI server when you have time?

Thanks!

**Comment by felixonmars** [comment]
Sadly Drone doesn't seem to allow multiple remotes to be enabled at the same time: https://github.com/drone/drone/issues/1336

**Comment by ghost** [comment]
@felixonmars thanks a lot for looking at it! So sad it doesn't work. @parched sorry we are not able to support Bitbucket right now, do you have any easy workaround for yourself?

**Comment by parched** [comment]
For the project I want to use tea for we do out development on Bitbucket but we have a mirror on GitHub. So it will still be useful, but it won't verify any pull requests before merging.
