### ISSUE TITLE
qmake generates differently on teaci/mingw32

### ISSUE THREAD

**Issue by parched** [TeaCI/tea-ci#3]
This passes on windows because it uses std=gnu++11 but on tea it uses std=c++11
https://tea-ci.org/parched/test/4
https://github.com/parched/test/commit/8c87a54f0c1ed7832d37308d4d4a4075a0b584fd

**Comment by ghost** [comment]
Hi @parched,

Thanks a lot for the report. Would you might test if it works with Qt4?

I'm on business trip and my network connection is slow right now, it takes me impossible time to download Qt5, but it seems I can't reproduce your case with Qt4.

```
fracting@codeweavers-ThinkPad-Edge-E431 MINGW32 /z/home/fracting/src/test
$ mingw32-make.exe
C:/msys32/mingw32/bin/mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory 'Z:/home/fracting/src/test'
g++ -c -pipe -march=i686 -mtune=core2 -O2 -frtti -fexceptions -mthreads -Wall -Wextra -DUNICODE -DQT_DLL -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_THREAD_SUPPORT -DQT_NEEDS_QMAIN -I'c:/msys32/mingw32/include/qt4/QtCore' -I'c:/msys32/mingw32/include/qt4/QtGui' -I'c:/msys32/mingw32/include/qt4' -I'c:/msys32/mingw32/include/qt4/ActiveQt' -I'release' -I'm_pi' -I'.' -I'c:/msys32/mingw32/share/qt4/mkspecs/default' -o release/main.o m_pi/main.cpp
g++ -Wl,-s -mthreads -Wl,-subsystem,windows -o release/m_pi.exe release/main.o  -L'c:/msys32/mingw32/lib' -lmingw32 -lqtmain -lQtGui4 -lQtCore4
mingw32-make[1]: Leaving directory 'Z:/home/fracting/src/test'

fracting@codeweavers-ThinkPad-Edge-E431 MINGW32 /z/home/fracting/src/test
$ ls release/
m_pi.exe  main.o
```

I can take deeper look with Qt5 once I'm free from current work on hand. In the mean time if you are able to narrow down the problem a little bit further that would be great appreciated.

**Comment by parched** [comment]
Hi @fracting thanks for testing, it shouldn't be a problem with qt4 because it doesn't support the c++11 CONFIG option so won't add a -std=gnu++11 or -std=c++11.

Ok I will do some more investigation and see what I come up with.

**Comment by parched** [comment]
I figured out the problem, teaci still uses qt 5.5 which didn't support c++11 in the same way. Could you update the mirror it pulls from?

**Comment by ghost** [comment]
@parched thanks a lot for debugging on the issue, I will work with @felixonmars to update the mirror.

**Comment by parched** [comment]
Thanks, I appreciate it. Tea ci will be really useful for us.

**Comment by ghost** [comment]
Update: still waiting on MSYS2's rsync support in order to update mirrors.tea-ci.org
It works before but broke for a while.

Once upgraded, we will introduce 64bit support this time.

**Comment by parched** [comment]
Thanks for the update. I have added an rsync fix here https://github.com/Alexpux/MSYS2-packages/pull/607

**Comment by ghost** [comment]
Thanks, while it might be related, but I'm mostly talk about rsync service of the repo itself, glad it works now:

```
rsync -rtlvHP --delete-after --delay-updates --safe-links repo.msys2.org::builds/ /srv/msys2/
```

**Comment by ghost** [comment]
Hi @parched, we just update both the repo and the Docker image, could you please retest? Thanks!

**Comment by parched** [comment]
Yes that fixed the issue, thank you.

**Comment by ghost** [comment]
Thanks for testing!

**Comment by ghost** [comment]
Note that mingw-w64-i686-toolchain is already preinstalled in the teaci/msys32 image, so you don't have to install again in your .drone.yml.
