### ISSUE TITLE
Badges not working

### ISSUE THREAD

**Issue by parched** [TeaCI/tea-ci#6]
Hi, the build status badges don't seem to be working., e.g., [![Build Status](https://tea-ci.org/api/badges/parched/LibrePilot/status.svg)](https://tea-ci.org/parched/LibrePilot)

**Comment by parched** [comment]
Actually maybe they do, I just need to specify branch

**Comment by n1tehawk** [comment]
I think I've run into a similar issue, so I'll put some more information here in case someone might find it useful.
- I my case, I had Tea CI set up (only) for an experimental branch in my repo - which in turn meant that there were no builds for the `master` branch.
- As long as that is the case, it seems that the default badge URL `https://tea-ci.org/api/badges/YOUR/REPO/status.svg` would return a **404 status**. If you put the URL into your browser, it should display a gray "_build: none_" badge. This seems to cause GitHub to not display the graphic properly.
- To get things working, you need to explicitly specify the branch name with an URL like `https://tea-ci.org/api/badges/YOUR/REPO/status.svg?branch=MYBRANCH`. Testing this with a browser should display the badge properly.

Regards, NiteHawk
